apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    name: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.laptopmonitoring.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.laptopmonitoring.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: {{ .Release.Name }}
      port: {{ .Values.laptopmonitoring.service.port }}
      targetPort: {{ .Values.laptopmonitoring.service.targetPort }}
  type: LoadBalancer
