name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: docker_login
        uses: docker/login-action@v3.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build an push
        uses: docker/build-push-action@v6
        with:
          context: ./LaptopMetricsApp
          file: ./LaptopMetricsApp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/systemmonitoring:latest

      - name: Log out from Docker Hub
        run: docker logout
